# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pack.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pack.proto',
  package='ye2libs.utils',
  serialized_pb='\n\npack.proto\x12\rye2libs.utils\"\x99\x02\n\x06Packet\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x12\n\ncrypt_type\x18\x02 \x02(\x05\x12\x0e\n\x06\x63ookie\x18\x03 \x02(\x0c\x12\x0f\n\x07\x66unc_id\x18\x04 \x02(\x05\x12\x0b\n\x03uin\x18\x05 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\x12\x10\n\x08ret_code\x18\x07 \x01(\x05\x12\x11\n\tdevice_id\x18\x08 \x01(\t\x12\x10\n\x08\x63ompress\x18\t \x02(\x05\"5\n\x05\x43RYPT\x12\x0e\n\nCRYPT_NONE\x10\x00\x12\r\n\tCRYPT_RSA\x10\x01\x12\r\n\tCRYPT_AES\x10\x02\"@\n\x08\x43OMPRESS\x12\x11\n\rCOMPRESS_NONE\x10\x00\x12\x10\n\x0c\x43OMPRESS_ZIP\x10\x01\x12\x0f\n\x0b\x43OMPRESS_7Z\x10\x02')



_PACKET_CRYPT = _descriptor.EnumDescriptor(
  name='CRYPT',
  full_name='ye2libs.utils.Packet.CRYPT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CRYPT_NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRYPT_RSA', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRYPT_AES', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=192,
  serialized_end=245,
)

_PACKET_COMPRESS = _descriptor.EnumDescriptor(
  name='COMPRESS',
  full_name='ye2libs.utils.Packet.COMPRESS',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMPRESS_NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPRESS_ZIP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPRESS_7Z', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=247,
  serialized_end=311,
)


_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='ye2libs.utils.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ye2libs.utils.Packet.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crypt_type', full_name='ye2libs.utils.Packet.crypt_type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cookie', full_name='ye2libs.utils.Packet.cookie', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='func_id', full_name='ye2libs.utils.Packet.func_id', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uin', full_name='ye2libs.utils.Packet.uin', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='ye2libs.utils.Packet.data', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret_code', full_name='ye2libs.utils.Packet.ret_code', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='ye2libs.utils.Packet.device_id', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compress', full_name='ye2libs.utils.Packet.compress', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PACKET_CRYPT,
    _PACKET_COMPRESS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=311,
)

_PACKET_CRYPT.containing_type = _PACKET;
_PACKET_COMPRESS.containing_type = _PACKET;
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET

class Packet(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKET

  # @@protoc_insertion_point(class_scope:ye2libs.utils.Packet)


# @@protoc_insertion_point(module_scope)
